plugins {
    id 'com.android.application'
}

android {
    namespace 'com.spike.mediapipe.benchmark'
    compileSdk 36

    defaultConfig {
        applicationId "com.spike.mediapipe.benchmark"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }


    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    def cameraxVersion = "1.5.0"
    implementation "androidx.camera:camera-core:$cameraxVersion"
    implementation "androidx.camera:camera-camera2:$cameraxVersion"
    implementation "androidx.camera:camera-lifecycle:$cameraxVersion"
    implementation "androidx.camera:camera-view:$cameraxVersion"

    implementation 'com.google.mediapipe:tasks-vision:0.10.35'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
}
